### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by egg82** [MicroRaft/MicroRaft#17]
Hello!

I've been absolutely loving using this project so far and would like to know how to donate to keep it going.
Will there be a link or similar in the future?

**Comment by metanet** [comment]
Hi @egg82 

Thanks for your interest in the project! I am super happy to hear that MicroRaft is useful for you. Currently I don't have any plan to run a donation program. But I would like to hear your feedback about the project and maybe some contributions :)

Cheers,

**Comment by egg82** [comment]
Well-documented, simple to use, and allows me to use my own transport quite easily. Additionally it uses a sane logging system. Very different from Ratis in all the right ways.

My only real complaint, I think, is the use of interfaces which supply no methods to implement and methods using those interfaces with no generics or overloads which lead to some confusion on my end as to what, exactly, I was supposed to be doing with RaftMessage before figuring out that there are specific message interfaces/types/layouts MicroRaft requires in the `model.message` package.

I'm having a similar problem with the LogEntry and StateMachine interfaces (I'm having trouble with the transferLeader throwing a timeout which I think might be related to my lack of handling for the UpdateRaftGroupMembersOp class, but I'm not entirely sure where that would go yet. Everything takes and returns Object or interfaces that might as well be an Object, which is *really* not helpful in attempting to understand what's supposed to happen)

Honestly, though, those are minor gripes when compared to eg. Ratis which has absolutely zero documentation and a metric ton of verbose output in info which causes a ton of console spam on eg. a Minecraft server.

I appreciate the hard work, and hopefully some day I can contribute more than just minor gripes. Money, obviously, is the easiest, but perhaps a PR down the line? Who knows!

**Comment by momiji** [comment]
@egg82 Are you still using this library? If so, is it available online so I can have a look when I'm totally lost?

**Comment by egg82** [comment]
> @egg82 Are you still using this library? If so, is it available online so I can have a look when I'm totally lost?

Apologies, I rarely check my Github notifications.
Yes, we're still using this library. Unfortunately, the project using it is private.
The project in question is (currently) used in the following YouTube videos:

https://www.youtube.com/watch?v=eLSc9ZZ1UJI
https://www.youtube.com/watch?v=wW8FnNghyvI
https://www.youtube.com/watch?v=VQY_m3wCBCE
https://www.youtube.com/watch?v=rdsXcS4guLQ
