### ISSUE TITLE
Feature Request : Distributed Transport Implementation or Sample

### ISSUE THREAD

**Issue by kitepad** [MicroRaft/MicroRaft#19]
Current version only have local transport (in single vm) sample.
Which version can provide real distributed transport implementation or sample?

**Comment by metanet** [comment]
sorry for my late response. i will publish code samples for distributed transport.

**Comment by kitepad** [comment]
Waiting ........

**Comment by metanet** [comment]
Hi @metanet 

Thanks for nudging me. Finally I completed the last bits and committed the project to https://github.com/MicroRaft/MicroRaft/tree/master/afloatdb. 

Please have a look.
