### ISSUE TITLE
Singleton leader role change reported before becoming leader

### ISSUE THREAD

**Issue by frajt** [MicroRaft/MicroRaft#20]
Hi, 

we are just looking how to monitor the role changes via the report listener. The method _toSingletonLeader_ seems to call the report listener before the state is changed to the leader. All other ROLE_CHANGE reports are invoked after the state is changed. Likely not working right.

>       publishRaftNodeReport(RaftNodeReportReason.ROLE_CHANGE);
> 
>         toLeader();
 
Thanks,
Michal

**Comment by metanet** [comment]
Hi Mical,

This publish call is for the FOLLOWER -> CANDIDATE state change: https://github.com/MicroRaft/MicroRaft/blob/master/microraft/src/main/java/io/microraft/impl/RaftNodeImpl.java#L1724-L1730

in `toLeader()` method, there is another publish call for the CANDIDATE -> LEADER change: https://github.com/MicroRaft/MicroRaft/blob/master/microraft/src/main/java/io/microraft/impl/RaftNodeImpl.java#L1143-L1148

You can see it in a test case here: https://github.com/MicroRaft/MicroRaft/blob/master/microraft/src/test/java/io/microraft/impl/SingletonRaftGroupTest.java#L84-L87

**Comment by frajt** [comment]
Indeed. I missed that it calls this.toLeader() and not state.toLeader(). Thank you.
