### ISSUE TITLE
Remove and add Raft node dynamically

### ISSUE THREAD

**Issue by roxrook** [MicroRaft/MicroRaft#21]
We're running a set of nodes and they can go up and down due to various reasons. I'm wondering if Microraft supports this behavior out of the box? Thanks. 
Btw great implementation 👏

**Comment by metanet** [comment]
yes, please see this api: https://github.com/MicroRaft/MicroRaft/blob/master/microraft/src/main/java/io/microraft/RaftNode.java#L378

you can also check this test class for some examples: https://github.com/MicroRaft/MicroRaft/blob/master/microraft/src/test/java/io/microraft/impl/MembershipChangeTest.java
