### ISSUE TITLE
[HELP] - Tips about leader election in Kubernetes pods

### ISSUE THREAD

**Issue by leandrocurioso** [MicroRaft/MicroRaft#23]
HI, I need to implement a leader election in kubernetes's pods.

So let's imagine that each pod is a container with its own IP address and will be a candidate to be the leader.

The leader will be responsible for some load and offload jobs and only the leader can do this jobs.

I read the docs and found the tutorial for AtomicRegister which is very nice btw, but as I understood the state machine will be replicated between the FOLLOWERS and LEADER and the Transport is local (Local means that runs in the same JVM Memory).

The point is how can I procede if I want for instance:

**"I want to use HTTP transport to keep all state machine synced each one in their specific JVM Memory?"**

Can someone give a light about that? 

Thanks for you time =)

**Comment by metanet** [comment]
Hi @leandrocurioso 

Thanks for checking out MicroRaft! 

The core library contains the Raft consensus implementation and some abstractions where you can write your impls and plug in to the core Raft code. Transport, StateMachine etc are these abstractions.

For a distributed implementation, you need to write your own Transport implementation. The AtomicRegister example uses a simple in-memory implementation for demonstration purposes.

I recently added a sample distributed key-value project which uses gRPC for communication. Please have a look here: 

I think it should give you some idea about how you can implement your use case.

Cheers,

**Comment by leandrocurioso** [comment]
Nice thanks for the feedback. I checked and solves my problem!
