### ISSUE TITLE
RaftStore.flush should give you the context wrt snapshot-driven log truncation

### ISSUE THREAD

**Issue by j-baker** [MicroRaft/MicroRaft#25]
The JavaDoc for RaftStore.persistSnapshotChunk reads:

```
     * After a snapshot is persisted at <em>index=i</em> and {@link #flush()} is called, the log entry at <em>index=i</em>, all
     * the preceding log entries, and all the preceding snapshots are no longer needed and can be evicted from storage. Failing to
     * evict stale entries and snapshots do not cause a consistency problem, but can increase the time to recover after a crash or
     * restart. Therefore eviction can be done in a background task.
     * <p>
```

This means that an implementer who'd like to implement this precisely could write something like:

```
long snapshotsPersistedUpTo = -1;

void persistSnapshotChunk(SnapshotChunk snapshotChunk) {
   persist();
   if (snapshotChunk.getSnapshotChunkIndex() == snapshotChunk.getSnapshotChunkCount() - 1) {
       snapshotsPersistedUpTo = snapshotChunk.getIndex();
   }
}

void flush() {
    flush();

    if (snapshotsPersistedUpTo != -1) {
        deleteStatePerhapsOnAnotherThread();
        snapshotsPersistedUpTo = -1;
    }
}
```

Reading the contracts of the methods, it's confusing as to whether this approach is correct. What if 'truncateSnapshotChunksUntil' is called in the meantime, for example? Reading the code, I know it's not, but it takes some digging into RaftNodeImpl and InstallSnapshotRequestHandler to figure out.

It'd be preferable to me as a user if 'flush' took a parameter of the most recent index which is known to have been a more recent (valid snapshot), that is to say:

```java
void flush(long deleteStateBeforeIndex) {
    flush();
    deleteStateBeforeOnAnotherThread(deleteStateBeforeIndex);
}
```

Then, the contract of `flush` changes to something like:

```java
   /**
     * Forces all buffered (in any layer) Raft log changes to be written to the storage and returns after those changes are
     * written.
     * <p>
     * When this method returns, all the changes done via the other methods have become durable. After these data are
     * durable, a store implementation may delete all log entries with a log index less than or equal to lowestRelevantIndex
     * and all snapshot entries with a log index less than lowestRelevantIndex. These deletes may be done concurrently with
     * normal execution if this is desirable.
     *
     * @throws IOException
     *         if any failure occurs during the flush operation
     * @see #persistLogEntry(LogEntry)
     * @see #persistSnapshotChunk(SnapshotChunk)
     * @see #truncateSnapshotChunksUntil(long)
     * @see #truncateLogEntriesFrom(long)
     */
void flush(long lowestRelevantIndex);
```

**Comment by metanet** [comment]
Hi @j-baker 

Thanks for creating this issue. It seems you are really diving into MicroRaft code! 

I think `flush()` can receive parameter of the latest snapshot index, and if a `flush()` call successfully makes changes of the given latest snapshot index durable, it can delete everything related to previous indices. This is a reasonable change. I may work on this if I can create some bandwidth, but I will make a relatively long travel soon, so I cannot deliver it before mid-October. If you have time, feel free to send a PR and I can review. 

Do you have a RaftStore impl that we can use for testing?

Btw, in your example code for `persistSnapshotChunk()`, please note that for a given snapshot index, chunks can be passed in any order since they are fetched from leader and other followers concurrently. Just fyi. I made a small commit to clarify this in the Javadoc.

**Comment by j-baker** [comment]
> Btw, in your example code for persistSnapshotChunk(), please note that for a given snapshot index, chunks can be passed in any order since they are fetched from leader and other followers concurrently. Just fyi. I made a small commit to clarify this in the Javadoc.

I discovered this later, but no fear, it is handled. I do actually have a RaftStore impl - it uses SQLite. Somewhat WIP! I suspect that at the very least, a standard 'RaftStore Tester' could be produced which sanity checks the guarantees a RaftStore should provide.

**Comment by metanet** [comment]
yeah I think it would be perfectly fine for testing. feel free to send a pr!

**Comment by metanet** [comment]
Hi @j-baker 

I have been playing with the RaftStore interface to make its contract a bit simpler and explicit. Please see it here: https://github.com/MicroRaft/MicroRaft/commit/bb4487024eaebb65c3252b6d0da4f475fa373b61

I would like to get your thoughts on the changes. 

Cheers,

**Comment by j-baker** [comment]
Yes, I think this represents what I had in mind. Left a couple of comments but the changes to the interface overall seem right to me. I should let you know that I've moved jobs and in my new job am actually writing no Java, so I'm sadly no longer a MicroRaft user. I'd be happy to do occasional code reviews or gut checks if that'd be helpful.

**Comment by metanet** [comment]
Thanks James for your review and offering help. Good luck with your new job!

**Comment by metanet** [comment]
Fixed by https://github.com/MicroRaft/MicroRaft/commit/8bec871527991cd727d6454f225d12dc80f62095
