### ISSUE TITLE
Explicit snapshot operation?

### ISSUE THREAD

**Issue by j-baker** [MicroRaft/MicroRaft#27]
I'd like to snapshot every 5 minutes, rather than every 50k messages. It's more understandable to the folks I work with. I'd also like to have schema migrations where I can stop handling certain old messages or change state machine behaviour, and after a snapshot is taken, those older messages can be discarded, thus indicating the end of a migration. I'd therefore like to trigger a snapshot explicitly after my migrations finish before reporting the result in telemetry (this is used by the CD system we use).

Is it advisable to (am I missing something) have this behaviour and how would you go about implementing an explicit snapshot operation? It looks like it could be as simple as just calling RaftNodeImpl.takeSnapshot using the right Executor but I'm not 100% on this.

Happy to provide any more details that'd be helpful!

**Comment by metanet** [comment]
Hi @j-baker 

I think I didn't fully understand the request. Do you request takeSnapshot() to be part of the public RaftNode API? Or do you mean a new config knob can be added to the RaftConfig to make nodes take a new snapshot every N seconds / millis? 

About the schema migration question, do you mean schema of the LogEntry objects themselves or the schema of the operations you replicate via LogEntry objects?

**Comment by j-baker** [comment]
- I would like takeSnapshot to be a part of the public RaftNode API somehow.
- Schema of the operations I'm replicated via LogEntry objects, not the schema of the LogEntry objects.

To go a little further into the use case:

The operations that I'm replicating are essentially protobuf style records - some number of fields. Occasionally, I'd like to make a change by providing some more information within a message, say by adding a new field.

To safely roll this out without taking downtime, I therefore need to do something like the following set of steps (assume the new field is called X):

1. Initial state: No nodes know about X.
2. Install a version where nodes know about X (as an optional field), and can handle both it being there and not being there.
3. Start sending messages with field X set.
4. When it is guaranteed that no node will see a message that does not contain X (*), one can mark X as required and remove the code that handles X not being present.

The problem I have is with (*). In a world without snapshotting, I may always have to handle X being absent because I am processing the entire history on startup. If I have snapshotted after (*), I am guaranteed to never see any message with X absent. I would like to be able to trigger a snapshot at the point where I know this.

Essentially, for most 'schema migrations' in a replicated state machine, the snapshot operation is the natural 'end' of the migration.

**Comment by metanet** [comment]
Ok. We can add a RaftNode#takeSnapshot() method which will trigger taking a snapshot by the local node without coordinating with the whole group. I will work on this.

**Comment by metanet** [comment]
@j-baker 

Please see https://jitpack.io/#MicroRaft/MicroRaft/v0.3 for the newly added `RaftNode#takeSnapshot()` method.
