### ISSUE TITLE
Is MicroRaft production ready?

### ISSUE THREAD

**Issue by RobinQu** [MicroRaft/MicroRaft#31]
I don't mean to be rude. microraft seems to be good option for me because it doesn't come with lots of built-in components like apache ratis. But I curious about whether this library has been tested in a production envrionment.

**Comment by metanet** [comment]
Hi @RobinQu 

Sure, no worries. Yes, the library is prod ready and it is being used in prod. Feel free to ask specific questions.

**Comment by RobinQu** [comment]
Awesome! I will have have a try this weekend.
