### ISSUE TITLE
Please publish jar packages  to maven central

### ISSUE THREAD

**Issue by RobinQu** [MicroRaft/MicroRaft#32]
For security reason, our CI server can only access a limited list of public repositories. Could you publish microraft packages to the maven central repository?

**Comment by metanet** [comment]
working on it.

**Comment by metanet** [comment]
@RobinQu 

I published the 0.4-SNAPSHOT version to the maven central repo. Please see it here: https://s01.oss.sonatype.org/content/repositories/snapshots/io/microraft/

I will publish the 0.5 version tomorrow.

**Comment by metanet** [comment]
https://s01.oss.sonatype.org/content/repositories/releases/io/microraft/microraft/0.4/

0.4 version is available in the maven central now.

**Comment by RobinQu** [comment]
Confirmed. Thanks!
