### ISSUE TITLE
[Question] Offloading RaftState snapshot persistence to RaftStore

### ISSUE THREAD

**Issue by gyakkun** [MicroRaft/MicroRaft#52]
Hi. Thank you for your great work. I'm recently working on a prototype of a lightweight distributed storage application and MicroRaft gives me outstanding flexibility regarding to its customizable transport layer. 

My question is, is it possible to totally offload the already snapshot pieces of the statemachine to RaftStore? I have this question because when I'm doing some stress testing of my app, it hits OOM and the heap dump shows the `RaftState.log.snapshot.operation` field which still holds `DefaultSnapshotChunkOrBuilder.operation` aka the snapshot chunks being accepted when taking snapshot eats up lots of memory. 

I formerly believed that it's been serialized and have a copy in the RaftStore and safe to move out of the memory, but it turned out not. To resolve this I need to heavily hack the `Serializer` implementation to make the snapshot chunks being hold on disk and vice versa when it's being deserialized for `InstallSnapshotRequest` RPC. 

My workload `operation`s for stress testing are thoudsands of ~1MB bytes[] (which I know is not very typical for Raft usage) using the microraft-sqlite as the RaftStore implementation, also the statemachine itself is a simple sqlite db. To save memory I have to make the snapshot chunk being written to disk (also a sqlite) first when taking snapshot and hold its address (say, an ID column of the sqlite table) in the chunk data structure, and work on the `Serializer` and `installSnapshot()` part, which in my opinion is not very neat. 

May I know if there's particular reason for holding two copies of the snapshot chunks in the `DefaultSnapshotChunk` implementation? Or should I say it's designed on purpose that totally up to us developers and the `RaftModelFactory` / `Serializer` / `RaftStore` implementations to decide how this snapshot and snapshot persistence behaviour should be? Thank you.

**Comment by metanet** [comment]
Hi @gyakkun 

Thanks for using MicroRaft!

I am not sure if I understood the question. Do you ask to why the last taken snapshot is held in `RaftLog.snapshot` and would it be possible to access the last taken snapshot from `RaftStore` instead of keeping an in-memory copy?

> May I know if there's particular reason for holding two copies of the snapshot chunks in the DefaultSnapshotChunk implementation?

`DefaultSnapshotChunkOrBuilder` keeps only 1 copy of the chunk object. Can you show me where we keep the second copy?

**Comment by gyakkun** [comment]
> I am not sure if I understood the question. Do you ask to why the last taken snapshot is held in `RaftLog.snapshot` and would it be possible to access the last taken snapshot from `RaftStore` instead of keeping an in-memory copy?
> 

Yes exactly what I mean.

**Comment by metanet** [comment]
I see. Yeah for large states having an in memory copy of the snapshot would create some overhead. It makes sense to rely only on the persistent copy eliminate this. I will try to take a stab at it in the upcoming weeks. If you would like to contribute, please feel free to submit a design proposal and a PR.

**Comment by gyakkun** [comment]
Thank you for replying. As it actually can be worked around somehow (the holder/proxy approch as mentioned above), I think for now it's not very critical to make an immediate change to tackle this.

Another finding on `microraft-sqlite` is, it seems storing all chunks of all snapshots. I previously thought it should only keep the latest chunks of the latest snapshot. May I know the reason for this design decision? Thank you.

**Comment by metanet** [comment]
Not a specific design decision. I think it was a small bug. I landed the fix here: https://github.com/MicroRaft/MicroRaft/commit/25fc07b91de74a670b9f4caf2a45b445eece780d. I will make a new MicroRaft release for this fix.

**Comment by gyakkun** [comment]
That's great. Let's keep this issue open for tracking until the new version published on maven. Thank you again for responding to user feedback.

**Comment by metanet** [comment]
https://github.com/MicroRaft/MicroRaft/releases/tag/v0.7 

0.7 should show up in the maven central in a couple of minutes.

**Comment by gyakkun** [comment]
Awesome!
